In [33]:
import time
import numpy as np
import pandas as pd
import tensorflow as tf

GRU_model = tf.saved_model.load('./GRU/1', tags=None, options=None)
RNN_model = tf.saved_model.load('./RNN/1', tags=None, options=None)

file = "./example_input.csv"
df = pd.read_csv(file, usecols=[19, 20, 21, 25, 26, 27], header=None)
df.columns = ['accel_x', 'accel_y', 'accel_z', 'gyro_x', 'gyro_y', 'gyro_z']

input = df.values.reshape(1, 1000, 6).astype(np.float32)

start = time.time()
output_gru = GRU_model(input)
end = time.time()

print("Time (GRU): ", end - start)
print("Time in ms (GRU): ", (end - start) * 1000)
print("Output (GRU): ", output_gru)

start = time.time()
output_rnn = RNN_model(input)
end = time.time()

print("Time (RNN): ", end - start)
print("Time in ms (RNN): ", (end - start) * 1000)
print("Output (RNN): ", output_rnn)

Time (GRU):  0.28224682807922363
Time in ms (GRU):  282.24682807922363
Output (GRU):  tf.Tensor(
[[[0.8065981  0.54687846 0.2792605  0.21243425 0.19723189]
  [0.9508189  0.6456507  0.1256944  0.05489716 0.04482185]
  [0.98314255 0.70317096 0.06610167 0.01903547 0.01442291]
  ...
  [0.9509814  0.00910699 0.14307682 0.59817255 0.9931962 ]
  [0.9731551  0.01043329 0.10060988 0.432361   0.98062587]
  [0.986334   0.01279209 0.06511406 0.2637896  0.9440662 ]]], shape=(1, 1000, 5), dtype=float32)
Time (RNN):  0.2998473644256592
Time in ms (RNN):  299.8473644256592
Output (RNN):  tf.Tensor(
[[[0.5576937  0.3966731  0.29789022 0.25793627 0.29082534]
  [0.68540704 0.26910362 0.13515835 0.06632127 0.10586473]
  [0.8461213  0.1179259  0.03021879 0.00527145 0.01623538]
  ...
  [0.03628332 0.01420726 0.02907273 0.02232377 0.9243987 ]
  [0.04697715 0.01252752 0.02413388 0.01614206 0.9156658 ]
  [0.06397144 0.01055226 0.01970582 0.01103285 0.9024854 ]]], shape=(1, 1000, 5), dtype=float32)
